### ISSUE TITLE
error TS2345: Argument of type ... is not assignable to parameter of type

### ISSUE THREAD

**Issue by Masber** [bpampuch/pdfmake#1500]
Hi,

how could I create an image with width using typescript?

```
pdfContent.content[0].columns[0].unshift(
{
    image: 'data:image/png;base64,' + this.label_logo,
    alignment: 'left',
    text: null,
    width: 150
} );
```

error message:

> ERROR in src/app/form-submit-carrier-job/form-submit-carrier-job.component.ts(744,17): error TS2345: Argument of type '{ image: string; alignment: string; text: null; width: number; }' is not assignable to parameter of type '{ image: string; alignment: string; text?: undefined; style?: undefined; } | { text: string; styl...'.
>   Object literal may only specify known properties, and 'width' does not exist in type '{ image: string; alignment: string; text?: undefined; style?: undefined; } | { text: string; styl...'.

any advice?

**Comment by liborm85** [comment]
I do not know much about typescript. But definition for `image` supported by pdfmake is:
```js
{
	image: '....',
	alignment: 'left',
	width: 150
}
```

**Comment by jquatier** [comment]
Seems like the check for undefined or null broke in 0.1.37. 
0.1.36 works fine.

I used to be able to pass `undefined` for `text` but now the images dont render, and if I pass `null` I get a different error.
This is useful when a block can be either text or an image based off a conditional.

Right now it looks like I'll have to remove the `text` property alltogether if its an image. Feels weird.

**Comment by liborm85** [comment]
Yes, if you want render `image` can not be defined `text` (because this means you want to create text not image.)

**Comment by jquatier** [comment]
Yeah except the absense of a property should be the same result as the property being set to undefined. This is standard practice for JavaScript.

This worked fine in 0.1.36, so I’ve pinned my code to that version.

Example 1:
{
   text: undefined
   image: “myimage.jpg”
}

Example 2:
{
   image: “myimage.jpg”
}

These 2 blocks should yield the same result. And they did in 0.1.36. Looks like in 0.1.37 the logic around was refactored, so example 1 no longer works.
